language: c
sudo: required
services:
  - docker
install:
  - docker pull avsm/docker-opam-build:debian-testing-ocaml-4.02.1
script:
  - echo "opam pin add -n cohttp.0.19.2 /repo" >> build.sh
  - echo "opam depext cohttp" >> build.sh
  - echo "opam install cohttp" >> build.sh
  - docker run -v ~/build/$TRAVIS_REPO_SLUG:/repo avsm/docker-opam-build:debian-testing-ocaml-4.02.1 aspcud -v
  - docker run -v ~/build/$TRAVIS_REPO_SLUG:/repo avsm/docker-opam-build:debian-testing-ocaml-4.02.1 sh -x /repo/build.sh
