language: c
sudo: required
services:
  - docker
install:
  - docker pull avsm/docker-opam-build
script:
  - docker run -v ~:/repo avsm/docker-opam-build:debian-stable-ocaml-4.02.1-system ls -la /repo
